### ISSUE TITLE
Binning width somewhat unexpected. 

### ISSUE THREAD

**Issue by niekdejonge** [matchms/ms2deepscore#220]
When working on MZMine integration I (or actually Robin) noticed that the binning is a bit weird. 

If the last bin does not completely fit within the set mz window it will not be used. So for instance:
mz_min = 0 mz_max =10 bin_width = 0.3. The last bin will end on 9.9. So any peak at 9.92 for instance would not fall in any bin even though it is below mx_max. 

Maybe it would be more intuitive to set the nr_of_bins and calculate the bin_width from there. 
But I am not sure if it is worth the refactoring (and likely not backwards compatible changes). 

@florian-huber Was there a reason for this way of implementing and do you think we should change this?

**Comment by florian-huber** [comment]
There was not particular reason that I remember.
In practice, this should not matter much for our typical number of 1,000 to 10,000 bins.

Using a number-of-bins instead would indeed fix the issue. But, on the other hand, setting a bin-width feels more intuitive to me, because I get a better sense of which peaks would later end up in the same bin. If we set this to a number of bins, we would get bins of width 0.1001 or 0.999 etc.

We could also add a remainder bin, so the one bin that is missing at the end?
(also not super intuitive... Would add a final 0.1 Da wide bin at the end in your example)

**Comment by niekdejonge** [comment]
I agree that it does not matter too much. For that reason I would actually argue to keep it as is. It is not fully intuitive, but the impact is so small, that it is not worth the refactoring and breaking backwards compatibility. So I will just close the issue.
