### ISSUE TITLE
Loading a torch model raises warning

### ISSUE THREAD

**Issue by julianpollmann** [matchms/ms2deepscore#252]
Hi,
loading a torch model over [here](https://github.com/matchms/ms2deepscore/blob/main/ms2deepscore/models/load_model.py#L34) will raise a warning with Pytorch > 2.

See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models

Not sure if just loading the weights is sufficient here.

**Comment by niekdejonge** [comment]
hi @julianpollmann Thanks for opening the issue! I didn't notice before. We have a similar issue open #236 
It is not very straightforward for us to change, since we have some tensorization settings of input data that are not always constant, that we would not be able to load in this way. 

I will close this issue, but feel free to add comments to #236

**Comment by florian-huber** [comment]
@niekdejonge from what I see Pytorch 2.6 now changed the default which moves this from a warning to an exception. So I think we should change the way we save/load the model.

--> #236
