### ISSUE TITLE
implement early stopping?

### ISSUE THREAD

**Issue by florian-huber** [matchms/ms2deepscore#59]
I ran a model training with early stopping and than got unexpected behavior of `model.save()` since that will now save the final model after training, hence ignoring any `save_best_only=True` setting.

**Comment by niekdejonge** [comment]
@florian-huber 
I believe I have a related issue.
I trained a new model using:

    checkpointer = ModelCheckpoint(filepath=model_file_name, monitor='val_loss', mode="min", verbose=1, save_best_only=True)
    earlystopper_scoring_net = EarlyStopping(monitor='val_loss', mode="min", patience=10, verbose=1)
history = model.model.fit(training_generator, validation_data=validation_generator,
                              epochs=150, verbose=1, callbacks=[earlystopper_scoring_net, checkpointer])

The model that is saved does only store the keras model and not the corresponding spectrum binner. (so it is not using the SiameseModel.save function) 

Possible explanation: I noticed I run model.model.fit() instead of model.fit(), since this returns the history. 

I found a quick hack, by recreating the spectrum_binner and resaving the model:

def save_model_with_spectrum_binner(filename: Union[str, Path], training_spectra):
    with h5py.File(filename, mode='r') as f:
        keras_model = keras.models.load_model(f)
    spectrum_binner = SpectrumBinner(10000, mz_min=10.0, mz_max=1000.0, peak_scaling=0.5,
                                     allowed_missing_percentage=10.0)
    spectrum_binner.fit_transform(training_spectra)
    SiameseModel(spectrum_binner, keras_model=keras_model).save("C:/Users/jonge094/PycharmProjects/PhD_MS2Query/ms2query/data/hot_topics_metabolomics/ms2deepscore_model_with_spectrumbinner.hdf5")

Do you know a way to make sure checkpointer saves the complete model (including spectrum binner) and storing the history?

**Comment by niekdejonge** [comment]
I think I found a solution for the early stopping not saving the best model. Just adding the parameter restore_best_weights=True to the early stopping. (maybe you already suggested this during our meeting) However, I do not really know how to test if this works as expected.
Checkpointer will still have the problem that it does not store the spectrum binning settings, since it uses the original keras save options. So I think the best solution is using early stopping but no checkpointer.
@florian-huber If you agree, you could close this issue

**Comment by florian-huber** [comment]
Outdated.
