### ISSUE TITLE
Add more flexible binning option

### ISSUE THREAD

**Issue by florian-huber** [matchms/ms2deepscore#88]
Now we used fixed size bins, but other choices might work even better. For instance peak sizes that increase with increasing m/z (to reflect higher ppm precision for low m/z ranges) or peak sizes that reflect the frequency of peaks within a certain m/z range (e.g. most high intensity peaks are in the 100-300m/z range for the GNPS dataset --> maybe one would want higher precision there?).

**Comment by florian-huber** [comment]
Started working on this in new branch...

**Comment by justinjjvanderhooft** [comment]
@florian-huber - be aware that below m/z 150, the mass accuracy may become less, especially below m/z 70. This really depends on the calibration that is done, and if a mass of around 70 is added to the calibration mix. Otherwise, the accuracy drops quite substantially for the lower masses. Within one experiment, this is not so much an issue for the binning, but across experiments, and to determine elemental formulas, it obviously is....

**Comment by florian-huber** [comment]
Outdated since new version will have different options anyway. Feel free to re-open or create a new one should this become relevant again.
